#!/usr/bin/env bash

source ~/.totally

CMD=$1
shift

function usage() {
	cat <<-USAGE >&2
	usage: $0 COMMAND ARG...
	
	Commands:
	
		deploy	Deploys the current project
		stop	stops the current project

	USAGE
	exit 1
}

function deploy() {
	echo deploy $@
}

case $CMD in
	"deploy") deploy $@ ;;
 	"stop") echo whatever bro ;;
 	*) usage ;;
esac

