#!/usr/bin/env bash


((ERRORS=0))
function error() {
	echo $@ >&2
	((ERRORS++))
}

function die() {
	error $@
	exit 1
}

function log() {
	# Log turned off by default
	# use --verbose to turn on logging
	:
}

function usage() {
	cat <<-USAGE >&2
	usage: $0 [--verbose] COMMANDS
	
	Commands:

		init	Initialise a new project
		deploy	Deploys the current project
		stop	stops the current project

	USAGE
	exit 1
}

function init() {
	local name=$(basename $PWD)
	echo NAME=\"$name\" > .totally
}

# Recurses up from the current directory all the way to the root
# directory looking for .totally files to source for configuration overrides
# Also sets LOCAL_ROOT - which should be the local project root
function configuration_walk() {
	if [ "/" != "$PWD" ]; then
		pushd .. >/dev/null
		configuration_walk
		popd >/dev/null
	fi
	
	[ -r $PWD/.totally ] && 
		log "Sourcing overrides from $PWD/.totally" && 
		source $PWD/.totally &&
		LOCAL_ROOT=$PWD # The last recursed $PWD should be the local project root
}

function validate_configuration() {
	[ -z "$DOCKER_SSH_HOST" ] && error "Missing docker host name env DOCKER_SSH_HOST"
	[ -z "$NAME" ] && error "Missing project name env NAME. Are you in a project? Have you run a totally init?" 
	(( ERRORS > 0 )) && 
		die "Add missing envs to a .totally file either in your home directory, or project directories."
}

function configure() {
	log Sourcing user defaults from ~/.totally
	source ~/.totally
	
	log Overriding with project overrides recursively till /
	configuration_walk $PWD

	[ -z "REMOTE_ROOT" ] && REMOTE_ROOT=totally/$NAME

	validate_configuration
}

function deploy() {
	configure
	echo deploying $NAME \($LOCAL_ROOT\) to $DOCKER_SSH_HOST:$REMOTE_ROOT
	sync
	# build new image
	# stop existing container
	# start new container
}


if [ -z "$1" ]; then
	usage
fi

while true; do
	CMD=$1
	[ -z "$CMD" ] && exit 0
	shift

	case $CMD in
		"--verbose") 
			function log() { echo $@ >&2; }
			log increased verbosity ;;
		"nop");;
		"deploy") deploy $@;;
		"init") init $@;;
	 	"stop") echo whatever bro ;;
	 	*) usage ;;
	esac
done
